// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4y92MdNkJBt4l6jFzh-_g-d8WQZVEDk',
    appId: '1:866895856160:web:97a861bd2b46bddf0d7245',
    messagingSenderId: '866895856160',
    projectId: 'authentication-e510e',
    authDomain: 'authentication-e510e.firebaseapp.com',
    databaseURL: 'https://authentication-e510e-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-e510e.appspot.com',
    measurementId: 'G-VVXVW62YB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6Qz3oH54xhlGlb7f4Ym7uNipKS9iQXA',
    appId: '1:866895856160:android:50cdd6127c1685640d7245',
    messagingSenderId: '866895856160',
    projectId: 'authentication-e510e',
    databaseURL: 'https://authentication-e510e-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-e510e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZYVNhQCN1z4yjDYjym32bNV7eLd6n1E',
    appId: '1:866895856160:ios:b59adc29a61336fd0d7245',
    messagingSenderId: '866895856160',
    projectId: 'authentication-e510e',
    databaseURL: 'https://authentication-e510e-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-e510e.appspot.com',
    iosClientId: '866895856160-s6qbm815sfeiesrq8mn63bu61a3u5ijc.apps.googleusercontent.com',
    iosBundleId: 'com.example.marvelHeroesYt',
  );
}
